version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - main: ./cmd/starsd/
    id: starsd    
    binary: starsd
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=netgo,faucet,ledger 
    ldflags:
      - -X "github.com/cosmos/cosmos-sdk/version.Name=Stargaze"
      - -X github.com/cosmos/cosmos-sdk/version.AppName=starsd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,faucet,ledger

release:
  github:
    owner: public-awesome
    name: stargaze
  draft: true
  prerelease: auto
